### PR TITLE
Nextcloud app as share target

### PR DESCRIPTION
**Pull request by SunboX**
this fixes issue #32

There are still some enhancements & tests open:

- [ ] check if the file already exists and ask if the user wants to overwrite it
- [ ] allow to create a folder on the share dialog
- [x] test multiple file upload
- [ ] ~~test "open with" functionality~~

please do not merge by now

### CODE REVIEW

**Comment by SunboX** [comment]
Seems the "save with" functionality does not work with WP10 anymore. There are various people having issues with the Cached File Contract:

* http://stackoverflow.com/a/41703829/1692735
* https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a49324b1-da98-4b7c-bb7c-78edd495ca8a/uwpwindows-phone-10-file-save-picker-not-working?forum=wpdevelop
* https://social.msdn.microsoft.com/Forums/windowsapps/en-US/dc95d8fe-6a89-42b1-8d07-984cacb42138/uwp-file-and-folder-pickers-do-not-work-on-build-14295?forum=wpdevelop

**Comment by SunboX** [comment]
I still have a lot of threading issues. Needs some more time.

**Comment by SunboX** [comment]
I still have a lot of "COM cast exceptions" if I open the app through the file sharing dialog of another app (for example the Photos app). This seems to be the same issue as mentioned here: http://stackoverflow.com/questions/35709776/invalidcastexception-on-sharetarget-windows-10-uwp
By now, I have no solution and no clue what's the source reason for this issue.

**Comment by SunboX** [comment]
I finally got rid of the thread exceptions by using a small trick. I will escape from the share view (widget view) by launching the "real" app using a protocol link and passing in all the files to share (as token).

I did read about this on stackoverflow here: http://stackoverflow.com/a/37495772/1692735

**Comment by SunboX** [comment]
There's still one more issue. The app will get disposed, if the share pane closes when calling `ShareOperation.ReportCompleted()` and the Debugger is not attached. This is the same issue as described here: http://stackoverflow.com/a/15075409/1692735

**Comment by SunboX** [comment]
I'm still trying to figure out, how the Facebook or the FB Messenger app has implemented the break-out from the share pane.

@altima or @DecaTec do you any idea?

**Comment by altima** [comment]
Facebook Apps are wrong to check. They are converted from the IOS App. Maybe check WhatsApp or Telegram. Is there any other Opensource project on Github?

BR altima

Von: André Fiedler
Gesendet: Sonntag, 30. April 2017 22:40
An: nextcloud/windows-universal
Cc: Enrico Meinel; Mention
Betreff: Re: [nextcloud/windows-universal] Nextcloud app as share target (#90)

I'm still trying to figure out, how the Facebook or the FB Messenger app has implemented the break-out from the share pane.
@altima or @DecaTec do you any idea?

**Comment by DecaTec** [comment]
Maybe you can have a look at this sample: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ShareTarget

When all the other issues are solved, I can take a look at this.

**Comment by SunboX** [comment]
@DecaTec I already read all the MS samples on Github. I initially used this. But the issues I have are not covered there.

I don't want to implement a new "app" for the share pane. I want to use what's already there. But Prism MVVM isn't playing well inside the share pane context.

The Facebook app somehow, escapes from this share pane. Most people suggest to launch by protocol link from the share activation. But the app get's closed after some timeout.

Facebook foes some trick, don't know how. You can see the app that opened the share pane for a short time after the big preloader and before the splash screen of the FB app.

**Comment by SunboX** [comment]
I now know, where the problem comes from. If you launch the app, MVVM will check if `Window.Current` is empty. If so, it will initialize it. Now the app gets suspended.

Next time you will share some files with the app, the app gets resumed. But because it's in the share pane, `Window.Current` is empty again. Now MVVM initializes it again. So by this time, the app is running with two "`Window.Current`". Multithreaded. But all the Service classes and stuff (like `NavigationService`, ...) is more or less bound to the first `Window.Current` (wrong Dispatcher aso.). So you will get a bulk of threading issues.

I already have a plan to work around it.

**Comment by SunboX** [comment]
@DecaTec or @altima 

It's working right now. Two points are open (see initial comment), but I would "fix" (add) them in a separate branch. By now there are a lot of changes here. Should be merged first.

**Comment by DecaTec** [comment]
I took a very short look at the changes. Looks good so far.
I think you can merge the PR and we should fix and bugs, etc. thereafter.

**Comment by SunboX** [comment]
Ok,merged it. Let's see what features I've broken 😏

**Pull request merged**
