### PR TITLE
#10 manual synchronization of folders

### PR DESCRIPTION
**Pull request by TheScientist**

### CODE REVIEW

**Comment by DecaTec** [comment]
I took a quick look at your PR.
Great work, looks good to me so far. 👍 

Some things which came up my mind:
- I would suggest that in the top (hamburger) menu, the sync item shouldn't be called "Synchronization Conflicts" because it then looks as there are always some conflicts. I would rather suggest calling it "Synchronisation Status".
- That being said, it would be great to have an additional tab ("sync history") showing the last sync activities (when was the last sync, which files have been synced, etc.). This way, it's more transparent to the user what's going on.
- I cannot sync the root folder ("/"), but only subfolders of it. Not sure how to handle it. Maybe there should be a sync button ("sync this folder") on the command bar (next to "sort" and "+").
- I think you have the info about which folders are synchronized because there's a menu entry "Stop Synchronizing". Maybe a good idea to mark synced folders with a special icon so that the user can see at a glance which folders are being synced. This may come in handy when we will support auto sync one day.
- When there is an error during sync, the error message is very generic ("Error while uploading File to nextcloud"). I don't want the user to stumble upon technical messages, but from my point of view, little more details would be great here.
- When looking at the "Sync Conflicts" on mobile (Lumia 950), it's not obvious that there is an additional entry in the hub menu and that you have to swipe to the left. Maybe this can be handled by renaming the menu entries to shorter terms ("Status", "Conflicts", "Errors").
- When calling the "Synchronization Conflicts" page, there seems to be a border around the content. Even more present on mobile.

**Comment by SunboX** [comment]
> I cannot sync the root folder ("/"), but only subfolders of it. Not sure how to handle it. Maybe there should be a sync button ("sync this folder") on the command bar (next to "sort" and "+").

Good idea, but I would put this in the "drop-out" of the command bar. It's not needed much, so we can hide it from the sreen. 😏 

All other points are valid, good catches!

**Comment by DecaTec** [comment]
@SunboX If this should be part of v1.1.0, we should merge it asap, because the PR is quite huge. The functionality works as far as I can consider, all the other things can be improved after the merge.

**Comment by SunboX** [comment]
I think this should be part of v1.1, there is some demand for it. Ok, I will try the changes one more in the current app - and if I'm satisfied with it (what I think will be so), I will merge it "as it is". Thanks for the hint.

**Comment by TheScientist** [comment]
@DecaTec  I agree with all your points, but my current focus lies on getting sync working as background task. So I'll fix some of the visual issues you mentioned but not more for now.

**Comment by DecaTec** [comment]
@TheScientist Absolutely no problem!
Most important should be that this PR gets merged. After that, I can help out at looking at all the small details.

So for now, I think you don't have to work on this PR anymore. Wait for the merge 😄 
As I've done some changes yesterday, it would be great if you can look at the merge conflicts (I hope for the last time).

**Comment by SunboX** [comment]
Thx @TheScientist & @DecaTec ! :smiley_cat:  Merged it. :ok_hand: There was a minor issue, I fixed it together with the merge. Works well for me. @DecaTec if you like, you can take a look at the changes, otherwise I will do it in some days. :smirk_cat:

**Pull request merged**
