### PR TITLE
Replaced WebDavClient by PortableWebDavLibrary NuGet package

### PR DESCRIPTION
**Pull request by DecaTec**
As already mentioned by mail, this is the pull request using my WebDAV library for the project.
This way we can pull the WebDAV logic out of the app itself.

See #17

### CODE REVIEW

**Comment by SunboX** [comment]
Wrong folder structure. 

## Steps to reproduce:

* create a folder named "a Folder"
* click on the newly created folder
* the same folder is listed inside itself
* if you delete this folder inside itself, "both" folders will be deleted

**Comment by SunboX** [comment]
## Error get's thrown
> Error while executing ListAsync (wrong response status code). Expected status code: 207 (MultiStatus); actual status code: 200 (Ok)

**Comment by DecaTec** [comment]
Atm I can't reproduce error 2. Can you please provide more details? Maybe a consequent error.

**Comment by SunboX** [comment]
Don't have the time right now, maybe today in the evening.

**Comment by DecaTec** [comment]
OK, I've already fixed problem 1 in the lib. As soon as you can provide some details about problem 2, I'll create new version of the lib and fix the app.

**Comment by DecaTec** [comment]
Some more changes:
- Updated WebDAV lib (bugfix for "folder in folder")
- Show folder sizes - see #52 
- Fixed a few things with paths (sometimes an additional '/' was added in front of the path)
- Added right click menu for debugging on Win desktop (and later on for the UWP app on desktop)

**Comment by SunboX** [comment]
Can not reproduce the second issue. I tested a little bit more, looks good to me! 👍

**Comment by DecaTec** [comment]
OK, then you can delete the WebDavClient files. I just removed it from the solution

**Comment by SunboX** [comment]
Thanks for the hint! Done.

**Pull request merged**
