### PR TITLE
Observable settings (and a few other things)

### LINKED ISSUE #50: Clear PasswordVault when resetting the app
After app reset you can log in with any password as long as server URl and user name are the same as before the reset.

When resetting the app we should call PasswordVault.Remove.

### LINKED ISSUE #53: Error after login "Invalid query, please check the syntax."
I'm getting this error from the app after I login in the application:
"Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:"

The steps to reproduce it:
1. login into the app
2. close the app
3. Open the app again and you get the error

I'm not a developer, but I just leave my prediction here (maybe it saves you time). The reason for the error seems to be because of GetUserAttributes method in NextCloudClient.cs, for some reason the App is sending a GET request to https://demo.nextcloud.com/ocs/v1.php/cloud/users/Test which returns this error.

```
 public async Task<User> GetUserAttributes(string username)
        {
            var response = await DoApiRequest(
                "GET",
                "/" + GetOcsPath(OcsServiceCloud, "users") + "/" + username
                );

            var responseStr = response;

            return GetUser(responseStr);
        }
```

App version: Nexcloud App from master branch commit 37cbc702f3d249911906f1f3cbf785896d7fc0e1
Server: demo.nexcloud.com

Screenshot of error:
wp_ss_20161130_0002 1

### PR DESCRIPTION
**Pull request by DecaTec**
I was working on using observable settings (see #27). I ran into some other problems which should also be fixed:
- Using observable Settings (#27)
- Prepared the app for storing settings in roaming profile (these will get synced across devices) - should be useful for the future. Settings should now only be accessed using the SettingsService (only the MigrationService used the local settings directly).
- Fixed #53 
- Fixed #50 (I'll comment on details there)
- Moved the reset of the PasswordVault on app reset to the SettingsService
- Set all calls to PasswordVault in try-catch (I had some problems while debugging)

### CODE REVIEW

**Comment by DecaTec** [comment]
Also prepared app for Windows Hello #44 (doesn't work yet, this seems not to be as simple as thought) and added a constants class for resources.

**Comment by SunboX** [comment]
> Also prepared app for Windows Hello

I did a Windows Hello Test App some months ago, that worked great. My time is limited right now, but I will take a look at it as soon as I get the time to.

**Comment by DecaTec** [comment]
I would have called the verification code in the App.xaml.cs (OnLaunchApplicationAsync). This does work for Windows Phone, but on the desktop the app get stuck.
My solution now would be to implement another page which is only there for Verification. This page is then called every time the app gets started or reactivated (and a corresponding setting is set).

**Comment by DecaTec** [comment]
Now I've added the option for Windows Hello in the settings.

Btw I've found a bug when running it on phone emulator with English locale: A resource for 'Download.Text' was missing, so the app crashed immediately after log in.

**Comment by DecaTec** [comment]
Now I've added a message when Windows Hello should be activated and is not available on the device (i.e. no PIN has been set). In such a case, only the message is shown and the option gets disabled again.

**Comment by DecaTec** [comment]
So, added the last bit for Windows Hello (#44).
There is now a Verification page handling all the Windows Hello stuff. As already mentioned, this could not be done in the App.xaml.cs.

But there's a major drawback, eventually a bug in Windows Hello at Windows Phone: When the app gets started for the second time (reactivated), then the UserConstentVerifier immediately returns the state 'Canceled'. I think it's a bug, because you can see the same behavior for other apps (e.g. OneDrive).

As a workaround, I've tried to mimic the behavior of the OneDrive app. They're showing an additional message when the fist authentication fails ('try again' - 'cancel').

On Windows desktop, it simply works as expected.

As I don't have any time for the next few weeks, please have a look at it (@SunBoX, @altima?). The pull request should be a good starting point for future development.

Btw: Can be messages shown by the DialogServices be centered on the screen?

**Comment by SunboX** [comment]
Thanks for your great work! I was sick for the last week and I'm still have to take drugs. :/ I will take a look as soon as I'm getting a bit time to. But it sounds really great!

On which platform do you want to display the message boxes centered? Mobile or Desktop or both? I left it by default, but we can change it.

**Pull request merged**
