### PR TITLE
added pin to start feature

### PR DESCRIPTION
**Pull request by altima**

### CODE REVIEW

**Comment by altima** [comment]
@SunboX please check :)

**Comment by SunboX** [comment]
Hey, great! Thanks for merging my changes in. :smirk:

I haven't time today. I will check it tomorrow. First look at the code looks good. Want to try it first. Don't know if the path stack is right if you pin a subfolder greater level 1. Let's see. :smile:

**Comment by SunboX** [comment]
Looks good to me. Two things I would change:

* rename "Pin" to "Pin to start"
* add "pin to start" method to secondary commands of the FileInfoPage CommandBar

**Comment by altima** [comment]
i will create a new pull request

**Pull request closed without merging**
