### PR TITLE
Updated to Portable WebDAV Library v0.6.3.0

### PR DESCRIPTION
**Pull request by DecaTec**
Updated to the latest version of the library (see [changelog](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/changelog.md)).

### CODE REVIEW

**Comment by DecaTec** [comment]
Could you please review this PR: I'm asking, because v0.6.3.0 is the last "traditional" version of the library (implemented as Portable Class Library).
I've started to port the project to .NETStandard 1.1 (.NET Core) and currently I'm preparing for a new release (v0.7.0.0). 

I've already tested the Nextcloud app with a preview release of the .NETStandard version of the PWL. Looks good so far. But we should update to the latest traditional version of the lib before integrating the .NETStandard version (some bigger code changes will be necessary then).

**Comment by altima** [comment]
Does work for me. @SunboX can I merge this?

**Comment by SunboX** [comment]
looks good to me, too. Merged. Thx! 👍

**Comment by DecaTec** [comment]
As we have a new project in there now, the reference to the WebDAV library should also be updated in the NextcloudClientPortable project.

**Pull request merged**
