### PR TITLE
Portable WebDAV Library 0.7.0.0

### PR DESCRIPTION
**Pull request by DecaTec**
- Added Portable WebDAV Library v0.7.0.0 (is now a .NETStandard 1.1 library).
- Some code changes because the interface to PWL has changed due to targetting .NETStandard.
- Added "Private Networks (Client & Server)" to NextcloudApp. I wasn't able to establish a connection to my test cloud without it.

### CODE REVIEW

**Comment by DecaTec** [comment]
Can you merge the PR to master? 
I'm asking because I'm up to releasing new version of the lib. Then we can update to the latest version asap.

Btw: Do you know a release date for the new version yet?

**Comment by SunboX** [comment]
Hey,

> Btw: Do you know a release date for the new version yet?

not now. It will be released, as soon as all open issues are fixed:
https://github.com/nextcloud/windows-universal/milestone/1

There's no timeline, just issues that have to be fixed. 😄 baby eating most of my spare time right now 😏

**Comment by DecaTec** [comment]
Thanks for the merge.

> baby eating most of my spare time right now :smirk:

That's totally OK.
What do you think about recruiting at least one more maintainer for this project who is willing (and has the time) to take a look at future PRs and merge them asap? Maybe we can speed up the development process a little...

**Comment by SunboX** [comment]
I've no problem with one more maintainer. But I think it's difficult to find one. And there's already @altima, who takes a look from time to time. But if you know someone more, let me know

**Comment by DecaTec** [comment]
Well, if it's of any help and you (and @altima) think an additional maintainer will be good for the project, count me in.
I don't have that much time, but willing to look over PRs etc. I can even contribute a little more as soon as my other project (Portable WebDAV Library) gets stable in the near future.

**Comment by SunboX** [comment]
Hey, I've added you as collaborator. You should get the invitation by email. Every help is welcome, and I think you know what you are doing. 😏 Feel free to merge something in and to organize issues. I will let you know if something isn't the way we want it.

**Comment by DecaTec** [comment]
Great, thanks.
I think you still habe my e mail address, just in case...

**Pull request merged**
